default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  host:     localhost
  port:     5432
  username: postgres
  password: postgres
  database: google_crawler_development

test:
  <<: *default
  host:     localhost
  port:     5432
  username: postgres
  password: postgres
  database: google_crawler_test

production:
  <<: *default
